apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  type: NodePort # Para poder aceder ao Grafana a partir do seu browser
  selector:
    app: grafana
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30000 # Aceda ao Grafana em http://localhost:30000