apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail-cluster-role
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: promtail
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: promtail-cluster-role
  apiGroup: rbac.authorization.k8s.io
