apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: promtail
        image: grafana/promtail:2.9.0
        args:
        - "-config.file=/etc/promtail/config.yml"
        volumeMounts:
        - name: config
          mountPath: /etc/promtail
        - name: positions
          mountPath: /tmp/positions
        # Montar a pasta de logs dos pods do host
        - name: docker
          mountPath: /var/run/docker.sock
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: promtail-config
      - name: positions
        hostPath:
          path: /tmp/promtail-positions
      # Mapear a pasta de logs do host para o volume
      - name: docker
        hostPath:
          path: /var/run/docker.sock
