apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  config.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki-service.monitoring.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # Extrai o nome do container do Pod para uma label
          - source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          # Extrai o nome do Pod para uma label
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          # Extrai o namespace do Pod para uma label
          - source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace