apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel-collector-service.monitoring.svc.cluster.local:8889']

      - job_name: 'otelcol-self'
        static_configs:
          - targets: ['otel-collector-service.monitoring.svc.cluster.local:8888']

      - job_name: 'microservice'
        metrics_path: /metrics
        static_configs:
          - targets: ['microservice.microservicetest-deployment.svc.cluster.local:8080']
