apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:2.4.1
        args:
          - "-config.file=/etc/tempo/config.yaml"
        ports:
        - name: http
          containerPort: 3200
        - name: otlp-grpc
          containerPort: 4317
        volumeMounts:
        - name: config-volume
          mountPath: /etc/tempo
        - name: storage-volume
          mountPath: /var/tempo
      volumes:
      - name: config-volume
        configMap:
          name: tempo-config
      - name: storage-volume
        emptyDir: {} # Para produção, use um PersistentVolumeClaim