receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  # ---- Traces → Tempo ----
  otlp/tempo:
    endpoint: tempo-service.monitoring.svc.cluster.local:4317
    tls:
      insecure: true

  # ---- Metrics → Prometheus ----
  prometheus:
    endpoint: "0.0.0.0:8889"

  # ---- Logs → Loki ----
  loki:
    endpoint: http://loki-service.monitoring.svc.cluster.local:3100/loki/api/v1/push
    tls:
      insecure: true
    # Loki doesn’t use “labels” anymore in config — instead, you can use attributes below
    default_labels_enabled:
      exporter: true
      job: true
      instance: true
      level: true
      service_name: true
  # ---- For debugging ----
  debug:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: "debug"
    metrics:
      address: "0.0.0.0:8888"   # <— EXPOSE self-metrics here
      level: "detailed"         # <— ensures exporter metrics like otelcol_exporter_sent_metric_points

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, debug]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, debug]
