global:
  scrape_interval: 15s # Intervalo padrão para fazer scrape

scrape_configs:
  # Job 1: Fazer scrape do próprio OpenTelemetry Collector para as suas métricas internas
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector-service.monitoring.svc.cluster.local:8888']

  # Job 2: Descobrir e fazer scrape de todos os pods anotados no cluster
  # Esta é a configuração mais importante e robusta para Kubernetes
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      # Manter apenas os pods que têm a anotação 'prometheus.io/scrape: true'
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      # Usar a anotação 'prometheus.io/path' para o caminho das métricas, se existir
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      # Usar a anotação 'prometheus.io/port' para a porta, se existir
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      # Usar o nome do namespace como label
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      # Usar o nome do pod como label
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

