apiVersion: v1
kind: Service
metadata:
  name: microservice
  namespace: microservicetest-deployment
spec:
  selector:
    app: microservice
  ports:
    - name: http
      port: 80
      targetPort: 8080