apiVersion: v1
kind: Service
metadata:
  name: microservice
  namespace: microservicetest-deployment
spec:
  type: NodePort
  selector:
    app: microservice
  ports:
    - name: https
      port: 80
      targetPort: 8080
      nodePort: 30007