apiVersion: v1
kind: Service
metadata:
  name: microservice
  namespace: microservice-staging
spec:
  selector:
    app: microservice
  ports:
    - name: http
      # The port the service is available on inside the cluster
      port: 80
      # The port on the pod to forward traffic to
      targetPort: 8080