# .github/workflows/build-and-push.yml

name: Build and Push to Docker Hub

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    # The type of machine to run the job on
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # registry: parameter is NOT needed for Docker Hub
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Use a Docker Hub access token here

      # 3. Build and push the Docker image to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Tag the image with your Docker Hub username, repo name, and a unique git SHA
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/microservicetest:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/microservicetest:${{ github.sha }}