name: Test, Build, and Push to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # CHANGE 1: Add the 'outputs' section to this job
    outputs:
      image_tag: ${{ steps.get_sha.outputs.SHA }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This new step gets the short git commit hash
      - name: Get short git SHA
        id: get_sha
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run unit tests
        run: dotnet test --no-restore --verbosity normal

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # CHANGE 2: We now tag the image with the unique git SHA, not 'latest'
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/microservicetest:${{ steps.get_sha.outputs.SHA }}

  deploy-to-production:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://localhost:8080 
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubectl for Production
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.PRODUCTION_KUBE_CONFIG }}" > $HOME/.kube/config
          echo "Kubeconfig configured for Production."

      - name: Deploy to Production Cluster
        run: |
          echo "Deploying image tag: ${{ needs.build-and-push.outputs.image_tag }}"
          kubectl set image deployment/microservice microservice=${{ secrets.DOCKERHUB_USERNAME }}/microservicetest:${{ needs.build-and-push.outputs.image_tag }} --namespace=microservicetest-deployment
      
      - name: Verify Deployment
        run: |
          echo "Waiting for deployment to complete..."
          kubectl rollout status deployment/microservice --namespace=microservicetest-deployment