name: Test, Build, and Push to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out your repository so the job can access your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up the .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # Match the SDK version in your Dockerfile

      # 3. Restore NuGet packages
      # This downloads all project dependencies before building or testing.
      - name: Restore dependencies
        run: dotnet restore

      # 4. Run unit tests
      - name: Run unit tests
        run: dotnet test --no-restore --verbosity normal

      # 5. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Build and push the Docker image to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/microservicetest:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/microservicetest:${{ github.sha }}
  deploy-to-production:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://localhost:8080 # A placeholder URL for your local service
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubectl for Production
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.PRODUCTION_KUBE_CONFIG }}" > $HOME/.kube/config
          echo "Kubeconfig configured for Production."

      - name: Deploy to Production Cluster
        run: |
          echo "Deploying image tag: ${{ needs.build-and-push.outputs.image_tag }}"
          # Use 'set image' to update the deployment with the specific new image
          # IMPORTANT: Replace 'microservicetest-deployment' with the name of your deployment in Kubernetes
          kubectl set image deployment/microservicetest-deployment microservicetest=${{ secrets.DOCKERHUB_USERNAME }}/microservicetest:${{ needs.build-and-push.outputs.image_tag }}
          
      - name: Verify Deployment
        run: |
          echo "Waiting for deployment to complete..."
          # This command waits for the update to finish and confirms it was successful
          kubectl rollout status deployment/microservicetest-deployment