name: Test, Build, and Push to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out your repository so the job can access your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up the .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # Match the SDK version in your Dockerfile

      # 3. Restore NuGet packages
      # This downloads all project dependencies before building or testing.
      - name: Restore dependencies
        run: dotnet restore

      # 4. Run unit tests
      - name: Run unit tests
        run: dotnet test --no-restore --verbosity normal

      # 5. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Build and push the Docker image to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/microservicetest:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/microservicetest:${{ github.sha }}